### ISSUE TITLE
is the new vendor_dir option functional?

### ISSUE THREAD

**Issue by daks** [devopsmakers/xterrafile#12]
I read in #6 than this option can be used to specify the destination directory *(instead of `-d` CLI argument)*.

I tried with the following Saltfile
```
vendor_dir: vendor/modules

nginx-formula:
  source: "https://github.com/saltstack-formulas/nginx-formula.git"
  version: "355a968a2bb34aaaf3db2eb54c5c0d0e2fcb5b09"

apt-formula:
  source: "https://github.com/saltstack-formulas/apt-formula.git"
  version: v0.9.0
```

and got the following error
```
$ ./bin/xterrafile install -f salt/production/Saltfile 
FATAL 2019/10/04 17:34:14 [salt/production/Saltfile] yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `vendor/...` into cmd.module
```

version used
```
$ ./bin/xterrafile version
xterrafile: version 2.0.0, commit 5eb7606, built at 2019-10-02T20:45:19Z
```
